name = "cv-martorell-worker"
main = "src/index.ts"
compatibility_date = "2024-11-01"
workers_dev = true

[triggers]
crons = ["0 6 * * 1"]  # cada dilluns a les 06:00 UTC

[[kv_namespaces]]
binding = "EQUIPS_DATA"
id = "75054d0638834cd18546bdbd8abdfbde"